//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentS2P2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingSystemDBEntities : DbContext
    {
        public BookingSystemDBEntities()
            : base("name=BookingSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HotelBedType> HotelBedTypes { get; set; }
        public virtual DbSet<HotelBooking> HotelBookings { get; set; }
        public virtual DbSet<HotelRoom> HotelRooms { get; set; }
        public virtual DbSet<HotelRoomService> HotelRoomServices { get; set; }
        public virtual DbSet<HotelRoomType> HotelRoomTypes { get; set; }
        public virtual DbSet<HotelRoomView> HotelRoomViews { get; set; }
        public virtual DbSet<PriceTable> PriceTables { get; set; }
        public virtual DbSet<SportBooking> SportBookings { get; set; }
        public virtual DbSet<SportDuration> SportDurations { get; set; }
        public virtual DbSet<SportFacility> SportFacilities { get; set; }
        public virtual DbSet<SportTimeSlot> SportTimeSlots { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
