//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentS2P2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoomService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelRoomService()
        {
            this.HotelBookings = new HashSet<HotelBooking>();
        }
    
        public int ServiceID { get; set; }
        public bool WiFi_Service { get; set; }
        public bool Room_Service { get; set; }
        public bool House_Keeping { get; set; }
        public bool Express_Queue { get; set; }
        public int Bed_Type { get; set; }
    
        public virtual HotelBedType HotelBedType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelBooking> HotelBookings { get; set; }
    }
}
