//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentS2P2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelRoom()
        {
            this.HotelBookings = new HashSet<HotelBooking>();
        }
    
        public int RoomID { get; set; }
        public int TypeID { get; set; }
        public int ViewID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelBooking> HotelBookings { get; set; }
        public virtual HotelRoomType HotelRoomType { get; set; }
        public virtual HotelRoomView HotelRoomView { get; set; }
    }
}
