//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentS2P2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportBooking
    {
        public int BookingId { get; set; }
        public string Booking_User { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int FacilityId { get; set; }
        public int TimeSlot { get; set; }
        public int Duration { get; set; }
        public decimal Price { get; set; }
        public int TransactionID { get; set; }
    
        public virtual User User { get; set; }
        public virtual SportDuration SportDuration { get; set; }
        public virtual SportFacility SportFacility { get; set; }
        public virtual SportTimeSlot SportTimeSlot { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
